name: MorningNotify

# cronで本来は使用しているがGitHub Actionsで実行しないように手動トリガー起動に変えます
# on:
#   schedule:
#     - cron: "30 1 * * *"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run Script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update results" || echo "No changes to commit"
          git pull --rebase
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
